### ISSUE TITLE
doesn't work :(

### ISSUE THREAD

**Issue by PA3DSS** [nicholasadamou/Raspberry-Pi-Auto-WiFi-Hotspot-Switch-Internet#2]
I installed the AP on my RPI3b+ , fresh install and up to date with latest Raspbian Stretch Lite, and nothing else is running, after reboot i can't login anymore with SSH, and no WiFi signal at all :(

**Comment by PA3DSS** [comment]
I forgot to mention anbout the kernel version:
uname -a
Linux 28 4.19.42-v7+ #1219 SMP Tue May 14 21:20:58 BST 2019 armv7l GNU/Linux

**Comment by nicholasadamou** [comment]
Thank you for bringing this to my attention. I will take a look when I have time!

**Comment by PA3DSS** [comment]
good luck !!
